targets:
  $default:
    builders:
      drift_dev:
        options:
          generate_connect_constructor: true
          apply_converters_on_variables: true
          scoped_dart_components: true
          write_from_json_string_constructor: true
          store_date_time_values_as_text: false
